### PR TITLE
2016.2 dev

### PR DESCRIPTION
**Pull request by stevefarmer01**

### CODE REVIEW

**Comment by dpefour** [comment]
Hi Steve,

Your pull request attempts to merge 2016.2-dev into the master branch which is not correct. The detailed log of the pull request shows many attempt merges across multiple apps.

To which Tcl App and Vivado release are you trying to contribute? Currently only 2016.2 is opened for contribution.

I have just checked and Vivado 2016.2 is currently pointing to Git branch 2016.2-dev. I’ll check whether this is expected or not. Nevertheless, if you are using Vivado 2016.2 than you should send the pull request to 2016.2-dev instead of master.

Thank you,
David

**Comment by stevefarmer01** [comment]
Hi Dave


Sorry I pressed the wrong button on the website. No pull request required.


Sorry for my incompetence.


....Steve


________________________________

**Comment by dpefour** [comment]
Hi Steve,

No problem, I just wanted to make sure you did not need further help.

Have a great 4th of July,
David

**Comment by dpefour** [comment]
Closing pull request per request from Steve.

**Pull request closed without merging**
