### PR TITLE
Added Tcl Profiler app

### PR DESCRIPTION
**Pull request by ncimino**
Please merge to 2016.1

### CODE REVIEW

**Comment by dbmccrohan** [comment]
Is this for me to GK?

**Comment by dbmccrohan** [comment]
Hey Dennis,

Yeah if you could please, then I'd appreciate that.  The main catalog needs to be updated and I think that's it.

-Nik

From: Dennis McCrohan
Sent: Thursday, December 17, 2015 15:48
To: Xilinx/XilinxTclStore
Cc: Nik Cimino
Subject: RE: [XilinxTclStore] Added Tcl Profiler app (#525)

Is this for me to GK?

**Comment by dbmccrohan** [comment]
There appears to be a problem with missing help:

############################################
  ## Procs Long Help
  ############################################
-W- missing long help for 'get_out_file' (/proj/cogsparusr/sandboxes/mccrohan/gatekeeper/525/XilinxTclStore/tclapp/xilinx/profiler/doc/get_out_file)
-W- missing long help for 'set_out_file' (/proj/cogsparusr/sandboxes/mccrohan/gatekeeper/525/XilinxTclStore/tclapp/xilinx/profiler/doc/set_out_file)
-I- found 4 procs with long help
-W- 2 procs have missing long help

  ##     ## ####  ######   ######  #### ##    ##  ######
  ###   ###  ##  ##    ## ##    ##  ##  ###   ## ##    ##
  #### ####  ##  ##       ##        ##  ####  ## ##
  ## ### ##  ##   ######   ######   ##  ## ## ## ##   ####
  ##     ##  ##        ##       ##  ##  ##  #### ##    ##
  ##     ##  ##  ##    ## ##    ##  ##  ##   ### ##    ##
  ##     ## ####  ######   ######  #### ##    ##  ######

-dm

**Comment by dbmccrohan** [comment]
I’m also seeing a couple of ERRORs when I run test.tcl for this app:

[cid:image001.jpg@01D13971.3A43E1F0]

Is this a problem? I would prefer if the test ran clean.

-dm

From: Dennis McCrohan
Sent: Friday, December 18, 2015 8:36 AM
To: 'Xilinx/XilinxTclStore'; Xilinx/XilinxTclStore
Cc: Nik Cimino; David Pefourque
Subject: RE: [XilinxTclStore] Added Tcl Profiler app (#525)

There appears to be a problem with missing help:

############################################
  ## Procs Long Help
  ############################################
-W- missing long help for 'get_out_file' (/proj/cogsparusr/sandboxes/mccrohan/gatekeeper/525/XilinxTclStore/tclapp/xilinx/profiler/doc/get_out_file)
-W- missing long help for 'set_out_file' (/proj/cogsparusr/sandboxes/mccrohan/gatekeeper/525/XilinxTclStore/tclapp/xilinx/profiler/doc/set_out_file)
-I- found 4 procs with long help
-W- 2 procs have missing long help

  ##     ## ####  ######   ######  #### ##    ##  ######
  ###   ###  ##  ##    ## ##    ##  ##  ###   ## ##    ##
  #### ####  ##  ##       ##        ##  ####  ## ##
  ## ### ##  ##   ######   ######   ##  ## ## ## ##   ####
  ##     ##  ##        ##       ##  ##  ##  #### ##    ##
  ##     ##  ##  ##    ## ##    ##  ##  ##   ### ##    ##
  ##     ## ####  ######   ######  #### ##    ##  ######

-dm

**Comment by ncimino** [comment]
Hey Dennis,

I added long help for set_our_file and get_out_file.

Those errors are expected and are negative tests.  The actual throw is caught.

-Nik

**Comment by dbmccrohan** [comment]
Ok, I started over again, but am seeing something else suspicious:

[mccrohan@xcordevl41 XilinxTclStore]$ git status
# On branch 2016.1-dev
# Your branch is ahead of 'upstream/2016.1-dev' by 5 commits.
#   (use "git push" to publish your local commits)
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   catalog/catalog_2016.1.xml
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       525.patch
#       catalog/2016.1/xilinx/profiler/
no changes added to commit (use "git add" and/or "git commit -a")

I don’t like (or expect) to see untracked files. David, any idea what is going on here?

-dm

**Comment by dbmccrohan** [comment]
These files are generated after the tclapp::update_catalog command is issued.

I'd also be concerned about:
  Your branch is ahead of 'upstream/2016.1-dev' by 5 commits.

To force your local repo into sync with 'upstream' (xilinx on GitHub) this is what I do:
WARNING: This is destructive!!! If you have work checked into your local branch that is not on the upstream server, then it will be lost.
Note: there is an ephemeral way to get it back
  git fetch upstream commit_branch
  git checkout commit_branch
  git reset --hard upstream/commit_branch

If you want to push these changes to your remote Fork of the repo, then use this command:
  git push origin commit_branch --force

When a Pull Request is received it will have a ref ID such as 123, and in this case I fetch that Pull Request using:
  git fetch upstream pull/<ID>/head:<BRANCH>

I use the same branch name as I use for the ID:
  git fetch upstream pull/123/head:123

At this point you can checkout that branch and work with it:
  git checkout 123

However, I generally want to merge this Pull Request, make changes, and submit a new Pull Request:
  git checkout commit_branch
  git fetch origin commit_branch
  git merge origin/commit_branch
  git merge 123
  <make my review changes / act as gate keeper>
  git commit -am "Merge pull request 123. Updated blah blah"
  git push origin commit_branch

-Nik

From: Dennis McCrohan
Sent: Friday, December 18, 2015 10:17
To: Xilinx/XilinxTclStore; Xilinx/XilinxTclStore
Cc: Nik Cimino; David Pefourque; Alec Wong
Subject: RE: [XilinxTclStore] Added Tcl Profiler app (#525)

Ok, I started over again, but am seeing something else suspicious:

[mccrohan@xcordevl41 XilinxTclStore]$ git status
# On branch 2016.1-dev
# Your branch is ahead of 'upstream/2016.1-dev' by 5 commits.
#   (use "git push" to publish your local commits)
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   catalog/catalog_2016.1.xml
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       525.patch
#       catalog/2016.1/xilinx/profiler/
no changes added to commit (use "git add" and/or "git commit -a")

I don’t like (or expect) to see untracked files. David, any idea what is going on here?

-dm

**Comment by dbmccrohan** [comment]
From: Nik Cimino
Sent: Friday, December 18, 2015 9:30 AM
To: Dennis McCrohan; Xilinx/XilinxTclStore; Xilinx/XilinxTclStore
Cc: David Pefourque; Alec Wong
Subject: RE: [XilinxTclStore] Added Tcl Profiler app (#525)

These files are generated after the tclapp::update_catalog command is issued.
[DM] I’m aware of that, but using David’s script for GKing these files don’t normally ever show up as untracked.

I'd also be concerned about:
  Your branch is ahead of 'upstream/2016.1-dev' by 5 commits.
[DM] Yes, that is also strange, I deleted my dbmccrohan/XilinxTclStore fork on github and re-forked from the master before I started. So I don’t think we should be seeing this.

To force your local repo into sync with 'upstream' (xilinx on GitHub) this is what I do:
WARNING: This is destructive!!! If you have work checked into your local branch that is not on the upstream server, then it will be lost.
Note: there is an ephemeral way to get it back
  git fetch upstream commit_branch
  git checkout commit_branch
  git reset --hard upstream/commit_branch

If you want to push these changes to your remote Fork of the repo, then use this command:
  git push origin commit_branch --force

When a Pull Request is received it will have a ref ID such as 123, and in this case I fetch that Pull Request using:
  git fetch upstream pull/<ID>/head:<BRANCH>

I use the same branch name as I use for the ID:
  git fetch upstream pull/123/head:123

At this point you can checkout that branch and work with it:
  git checkout 123

However, I generally want to merge this Pull Request, make changes, and submit a new Pull Request:
  git checkout commit_branch
  git fetch origin commit_branch
  git merge origin/commit_branch
  git merge 123
  <make my review changes / act as gate keeper>
  git commit -am "Merge pull request 123. Updated blah blah"
  git push origin commit_branch

-Nik

From: Dennis McCrohan
Sent: Friday, December 18, 2015 10:17
To: Xilinx/XilinxTclStore; Xilinx/XilinxTclStore
Cc: Nik Cimino; David Pefourque; Alec Wong
Subject: RE: [XilinxTclStore] Added Tcl Profiler app (#525)

Ok, I started over again, but am seeing something else suspicious:

[mccrohan@xcordevl41 XilinxTclStore]$ git status
# On branch 2016.1-dev
# Your branch is ahead of 'upstream/2016.1-dev' by 5 commits.
#   (use "git push" to publish your local commits)
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   catalog/catalog_2016.1.xml
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       525.patch
#       catalog/2016.1/xilinx/profiler/
no changes added to commit (use "git add" and/or "git commit -a")

I don’t like (or expect) to see untracked files. David, any idea what is going on here?

-dm

**Pull request merged**
