### PR TITLE
983438 - reference xilinx_vip packages for the non-precompile simulation flow

### PR DESCRIPTION
**Pull request by rajklair**
GK: please merge to XilinxTclStore master branch (xsim app, priority-p1). Thanks.

### CODE REVIEW

**Comment by rajklair** [comment]
Please update 2017.3 and 2018.1 catalogs. Thanks

**Comment by binochotta** [comment]
If the changes are needed for 2018.1, you have to modify 2018.1-dev branch. Updating 2018.1 catalog on master branch will not work as P4 automation is pulling content from 2018.1-dev git branch.
Thanks,
Bin

**Comment by rajklair** [comment]
Thanks. I will publish to 2018.1-dev separately. Please update 2017.3 catalog only.

**Comment by dbmccrohan** [comment]
I looks like there are merge errors when I reach step 7 of the merge flow<http://confluence.xilinx.com/display/XSW/Tclstore+Gatekeeper+Checklist>:


tclstore update_repo -repo . -merge 605 -v
-I- Start logging messages to '/proj/cogsparusr/sandboxes/mccrohan/tmp/tclstore/605/tclstore.log' on Tue Sep 12 14:24:32 MDT 2017.

-I- git: /tools/batonroot/rodin/devkits/lnx64/git-1.9.5/bin/git
-I- git version: 1.9.5
-I- curl: /usr/bin/curl
-I- current Git branch '2017.3-dev'
-I- merging a pull request (605) on branch '2017.3-dev' (upstream::refs/pull/605/head)
-E- Git command failed
     -------------------------------------------------------
     Auto-merging catalog/catalog_2017.3.xml
     CONFLICT (content): Merge conflict in catalog/catalog_2017.3.xml
     Automatic merge failed; fix conflicts and then commit the result.
     From https://github.com/Xilinx/XilinxTclStore
      * branch            refs/pull/605/head -> FETCH_HEAD
     -------------------------------------------------------
-I- Git log for branch '2017.3-dev' (last 2 commits)
     926ad0e83f77f7098d2e98b32f1c45c3f69df216 -update catalog
     2eb41d35d04958a146aa7722b0274fbd17296de5 write_project_tcl - fixes related to rm and bd creation
-I- reverting to Git branch '2017.3-dev'
-E- Git command failed
-I- reverting to Git branch '2017.3-dev'
-E- Git command failed
catalog/catalog_2017.3.xml: needs merge
error: you need to resolve your current index first
-I- Stop logging messages to 'tclstore.log' on Tue Sep 12 14:24:34 MDT 2017.

Raj, can you please look into this and generate a new pull request?

-dm

**Comment by dbmccrohan** [comment]
Close/reject due to merge conflicts.

**Pull request closed without merging**
