### PR TITLE
removed unneeded call to generate_mem_files, CR:948099

### PR DESCRIPTION
**Pull request by ncimino**
Please merge to 2016.1.  This pull request is pending SRCB approval.

### CODE REVIEW

**Comment by dbmccrohan** [comment]
Per our discussion yesterday, Raj needs to review this and forward to GK.

-dm

**Comment by ncimino** [comment]
Raj, Please merge to 2016.1.

**Comment by binochotta** [comment]
Thanks,
Bin

On Mar 30, 2016, at 10:28 AM, Nik Cimino <notifications@github.com<mailto:notifications@github.com>> wrote:


Raj, Please merge to 2016.1.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/Xilinx/XilinxTclStore/pull/561#issuecomment-203540786>


This email and any attachments are intended for the sole use of the named recipient(s) and contain(s) confidential information that may be proprietary, privileged or copyrighted under applicable law. If you are not the intended recipient, do not read, copy, or forward this email message or any attachments. Delete this email message and any attachments immediately.

**Comment by ncimino** [comment]
We have now received SRCB approval for this change.  I have contacted Raj.

**Comment by dbmccrohan** [comment]
Great. Raj, if you could get to this before lunch today it would be appreciated.

-dm

**Pull request closed without merging**
